travis:
  secure:
    BINSTAR_TOKEN: Xyiivhqy+aS2mJ4xnraDeYmywUZ1gQMAX7mGoV4JOmA/LpkU+MKYhznWlpfTULWrQ8S8dAPDOnoDEgdICKQ3UaHLefLH4t1YjJYSjBk5F7WWq1AFTjTEe6SyNuORTz8GjgPz8ZX8ZFbEITqfdVjoSIRac6cWKDTUWTiTa8YZJjY/5ehmnkA1k+zkZIbkvPstK7VJEE7c20mPpI7wsWuarMc1SnRDbXNbfH/m/8JKTQbh6mi8nCMPJZZmWHp2c8sPqwsV+FBjMCGvWq8eW46ijSett5vy15SGBm00wvJHUBn0Immai5sj5FAZqjFjI5LOPI1u+jWo6dOiHyZnH+vW78QCpkyf9oF8iHdZENBbc7b+FB31s9NMQZsPoaIqarH9/tkaNh/uYD+vZ4aaGB8z/kWerKm6Yc7rb9ziWxGAKSTZdfdUG2FeBLI7KgPxuSd/bEiIMydKsOtwpw0S4r73n7YmOwq733RZgjf3AShKPWxknpOUb3nZ14B8uSxNLhC/+dtpUhD1qA5tAh8BqV1Z9zk7hdqf0cuOjXuYhzXY0jQkkv9PoVLjJbs71pxFSp0A6/4811eFK8W5iGMsG+CM4frGuWXxr3fuQbqMxQDuIGCrOMnGK7RpQZTEjLfH7fR32eQJpgJatVOsj/3tgAvQFEG07y7of3VXRCmU3Jav7cQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
